# Spring Boot configuration
spring:
  # Database
  datasource:
    # Note! Openshift setup
    url: jdbc:postgresql://localhost:5432/testDb
    username: emil
    password: 1234
    driverClassName: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:migrations/changelog.groovy
    url: jdbc:postgresql://localhost:5432/testDb
    user: emil
    password: 1234
    default-schema: public
server:
  port: 8085